Tutorial 4: Pioneer WEC
sandialabs/WecOptTool pull request #243
Opened 2023-05-25 05:21 UTC by michaelcdevin

## Description
Tutorial showcasing the Pioneer WEC: https://github.com/SNL-WaterPower/pioneer_wec

## Type of PR
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation
- [x] Other: **Tutorial**

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/sandialabs/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on *your* fork, to the [main branch in WecOptTool](https://github.com/sandialabs/WecOptTool).
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2023-06-24 01:17 UTC, michaelcdevin commented
Positions amplitudes and phases are nearly matching in the verification case, though WecOptTool is still having a slight change in amplitude for some reason. PTO velocity is still twice what it is in Mark's Python script, but the mean power is about half?

**WecOptTool**:
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/49c30158-0f61-4ba2-bcda-b9f363873dd1)

**Mark's script**:
![comparison_2500MaxTrq_pos](https://github.com/sandialabs/WecOptTool/assets/52984639/78a85f64-fa55-4e6a-89f0-08b1b6ed9af9)
![comparison_2500MaxTrq_vel](https://github.com/sandialabs/WecOptTool/assets/52984639/3f6a10cb-b316-4b32-b809-48cd506ac326)

2023-06-27 00:55 UTC, michaelcdevin commented
After some more tweaks, all the positions are lining up with Mark's reference script, but the velocity in WecOptTool is not lining up with its position for some reason... still investigating this.
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/f90859cc-cb97-415c-a10d-37f360f7c32c)

2023-06-27 16:46 UTC, michaelcdevin commented
More tweaks, and the validation case is now very close to matching. Note that unlike the previous plot above, this has the transient in the reference case removed by running the reference case 3x the length of the WecOptTool time series, then removing the first 2/3rds. The mean mechanical power is still a few watts lower in WecOptTool than the reference case, but I have verified that WecOptTool is converging to the correct motor damping and both cases have matching hydro coefficients, spring properties, waves, time vector, and flywheel + buoy properties. I suspect the difference is due to remaining transient effects in the reference case, which seem to dissipate very slowly after the first 30 seconds.
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/9610ae6e-8658-4139-894c-13395781519c)

2023-06-28 19:48 UTC, michaelcdevin commented
The spring force was acting in the wrong direction! After changing the sign, we're now getting excellent agreement between WecOptTool and Mark's script. I also realized there was a PTO frame of reference issue I wasn't accounting for, so the power in WecOptTool is now negative as expected (I also flipped this in Mark's script to match, since this is just a sign convention thing). Now to actually convert the validation case into an optimization problem.
![image](https://github.com/sandialabs/WecOptTool/assets/52984639/29b89258-af81-4cf8-9336-81ebf6bea08c)

2023-07-05 23:55 UTC, michaelcdevin commented
For reference, here's the script to generate the validation plots shown above
[Pioneer_validation.zip](https://github.com/sandialabs/WecOptTool/files/11962858/Pioneer_validation.zip)

2023-07-11 20:22 UTC, cmichelenstrofer requested changes

2023-07-11 20:22 UTC, cmichelenstrofer commented on docs/source/tutorials.rst
> +    - :doc:`_examples/tutorial_4_Pioneer`: One part examples with custom PTO physics and modeling both hydrodynamic and non-hydrodynamic degrees of freedom.
```suggestion
    - :doc:`_examples/tutorial_4_Pioneer`: Example with custom PTO physics and modeling both hydrodynamic and non-hydrodynamic degrees of freedom.
```

2023-07-11 20:22 UTC, cmichelenstrofer commented on wecopttool/core.py
> +        _log.warning(
this should be inside an `if` statement. Currently prints the warning for all DOFs no matter what.

2023-07-12 14:46 UTC, ryancoe commented on wecopttool/core.py
> +        _log.warning(
I'd also suggest we leave the default behavior as-is and only use this new method (shift negative elements to threshold) based on an optional argument

```python
check_linear_damping(..., method='shift up'):
...
if method == 'shift all':
    (do current old/existing method)
elif method == 'shift elements':
    (do new proposed method)
end
```

2023-07-12 17:23 UTC, michaelcdevin commented on wecopttool/core.py
> +        _log.warning(
Thanks for catching this @cmichelenstrofer, I did this locally but forgot to save before committing.

Great suggestion @ryancoe, this has been added as of [cc3a498](https://github.com/sandialabs/WecOptTool/pull/243/commits/cc3a49817ef5d6c760d5f81760b087e78541eb87).

2023-07-13 14:11 UTC, cmichelenstrofer approved these changes

2023-07-13 14:13 UTC, merged