Saturated feedback controllers
sandialabs/WecOptTool pull request #273
Opened 2023-10-09 21:27 UTC by cmichelenstrofer

## Description
This PR adds the ability to saturate (symmetric or asymmetric max and min forces) the PTO force from PID controller. 

## Type of PR
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation
- [ ] Other: (specify)

## Checklist for PR
- [ ] Authors read the [contribution guidelines](https://github.com/sandialabs/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [ ] The pull request is from an issue branch (not main) on *your* fork, to the [main branch in WecOptTool](https://github.com/sandialabs/WecOptTool).
- [ ] The authors have given the admins edit access
- [ ] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details
This feature has been requested multiple times. See #269

2023-10-10 15:58 UTC, ryancoe commented
@cmichelenstrofer - for the off-diagonal elements, are you doing anything to enforce symmetry?

2023-10-16 15:51 UTC, cmichelenstrofer commented
example notebook: [saturated_pi.ipynb.zip](https://github.com/sandialabs/WecOptTool/files/12918996/saturated_pi.ipynb.zip)

2023-10-20 22:42 UTC, ryancoe requested changes
probably worth a quick meeting to discuss this

2023-10-20 22:42 UTC, ryancoe commented on wecopttool/pto.py
> +            tmp = np.clip(force_td_tmp[:,i], f_min[i], f_max[i])
Is there any reason we could not do this same thing in `controller_unstructured`?

2023-10-20 22:42 UTC, ryancoe commented on wecopttool/pto.py
> +    saturation: Optional[FloatOrArray] = None,
The way we're repeating these function signatures (which is not new to this PR) makes me wonder whether we should have a controller class...

2023-10-20 22:42 UTC, ryancoe commented on tests/test_pto.py
I'm thinking it would be a good idea to add an integration test to check if the saturated PI solution matches a constrained unstructured solution for a regular wave.

@cmichelenstrofer - Do you have the code you used to generate this result: https://github.com/sandialabs/WecOptTool/issues/269#issuecomment-1751342256? Here's my attempt: [test_saturated_pi.ipynb.zip](https://github.com/sandialabs/WecOptTool/files/13059030/test_saturated_pi.ipynb.zip). The two solutions are certainly close, but there's some (numerical?) discrepancy - probably related to `nsubsteps`?

![image](https://github.com/sandialabs/WecOptTool/assets/5589887/e6a18a47-38e7-45e6-aaa2-6fe835d51c39)

2023-10-23 17:04 UTC, ryancoe commented on wecopttool/pto.py
> +    saturation: Optional[FloatOrArray] = None,
See #283

2023-10-26 23:17 UTC, ryancoe commented on tests/test_integration.py
> +            pto_fdom[key], pto_tdom[key] = pto[key].post_process(wec[key],
@cmichelenstrofer - I'm trying to get the comparison you showed in https://github.com/sandialabs/WecOptTool/issues/269#issuecomment-1751342256 into our integration tests. I probably need to add scaling, maybe specific to each controller. Will also need to see how long this takes to run (currently a lot), as I don't want to add too much time to CI.

2023-11-10 17:34 UTC, ryancoe commented
@cmichelenstrofer - I can't seem to assign you as the reviewer for this, but can you please take a final look at what I've added in `test_integration.py` and then merge if you're happy?

2023-11-10 20:06 UTC, ryancoe approved these changes

2023-11-10 20:11 UTC, cmichelenstrofer commented on tests/test_integration.py
> +
```suggestion

```

2023-11-10 20:12 UTC, merged