Test capytaine lids
sandialabs/WecOptTool pull request #363
Opened 2024-08-01 18:41 UTC by jtgrasb

## Description
This PR uses Capytaine’s new internal lid feature to remove irregular frequency spikes from the BEM results for each of the 4 tutorials. The irregular frequency spikes mostly occur in the added mass and radiation damping but may also impact the excitation forces. The internal lid does not completely remove irregular frequency spikes, but it moves them to higher frequencies (ideally above frequency range of interest). The mesh size and lid position can be tuned to move the spikes outside the frequency range of interest.

## Type of PR
- [X] New feature

## Checklist for PR
- [X] Authors read the [contribution guidelines](https://github.com/sandialabs/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [X] The pull request is from an issue branch (not main) on *your* fork, to the [dev branch in WecOptTool](https://github.com/sandialabs/WecOptTool/tree/dev).
- [X] The authors have given the admins edit access
- [X] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details
WaveBot: The wavebot uses a frequency array containing 10 frequencies up to about 18 rad/s. The impact of irregular frequencies is small, but there is an impact to the result at about 5.6 rad/s where the added mass and radiation damping are lower without the internal lid. In tests of a more discretized frequency array, the irregular frequency spike was found to line up with about 5.6 rad/s, confirming the cause of this discrepancy. Note, I also needed to decrease the mesh size factor from 0.5 to 0.2 to move this frequency spike fully outside the range of interest.
<img src="https://github.com/user-attachments/assets/cdf7b27d-2f75-451d-87a8-71e262abe51c" width="350"> <img src="https://github.com/user-attachments/assets/18dea568-c77c-4bf1-bb66-6cc98496aaee" width="350">

Aquaharmonics: The AH tutorial uses a frequency array containing 10 frequencies up to about 8 rad/s. When testing a more discretized frequency array, there is a small spike within the array, but this does not show up in the 10 frequencies as shown below. Still, I applied the lid as it will be useful if users change the frequency array at all.
<img src="https://github.com/user-attachments/assets/6e4f2b4a-73fc-412b-a89e-cf43e626c825" width="350"> <img src="https://github.com/user-attachments/assets/e7fbd956-70d4-4a4a-958b-279eb4093a76" width="350">

The LUPA example is unique because the float body has a hole in the middle (often referred to as a moonpool). The frequency spike caused by the moonpool is real and cannot be removed with the standard lid. We already have an option to fill the hole in to remove the frequency spike and this works fine for removing the frequency spike. I could also try a lid that goes over the whole float (including the hole) if its worth checking. The internal lid does not improve the BEM results. Actually, it changes the magnitude of results for some dofs (pitch). I will make an issue on Capytaine to ask about this change.
<img src="https://github.com/user-attachments/assets/048ba74a-5885-4888-b41d-6e3c6f847ca4" width="380"> <img src="https://github.com/user-attachments/assets/ab4df9a1-7d03-4f14-98b4-233152973eb9" width="380">

Pioneer: Adding a lid to this tutorial along with reducing the mesh size factor from 0.5 to 0.3 was able to remove the frequency spikes as shown below. This led to a slight change in the power results (~2 W for regular waves).
<img src="https://github.com/user-attachments/assets/d1441f02-31e2-4f6a-bdf4-aa62ae62e184" width="350"> <img src="https://github.com/user-attachments/assets/d1dfacbe-4cbf-454e-bd93-e0cc846749cc" width="350">

2024-08-20 19:12 UTC, jtgrasb commented
I still want to do some testing of the computation time with the new mesh refinements and the lids, but other than that, the PR is ready to be reviewed.

2024-09-26 18:25 UTC, jtgrasb commented
I tested the computation time of the BEM runs for each of the tutorials before and after adding the lids. Both the AquaHarmonics and LUPA tutorials have basically no change in computation time with the lid applied. The WaveBot and Pioneer both have significantly increased computation time, but this is due to the refined mesh (reduced mesh_size_factor from 0.5 to 0.2) to help eliminate frequency spikes.

<img width="622" alt="image" src="https://github.com/user-attachments/assets/6eba7880-f165-4d8f-b34a-038a2965fabf">

2024-10-24 20:41 UTC, ryancoe commented
@dtgaebe will review

2024-10-29 16:18 UTC, dtgaebe requested changes
Looks pretty pretty good, maybe some minor changes for someone who just jumps into Tutorial2.

2024-10-29 16:18 UTC, dtgaebe commented on examples/tutorial_2_AquaHarmonics.ipynb
> +    "Again, we add a lid mesh to remove irregular frequency spikes.\n",
```suggestion
    "We add a lid mesh to remove irregular frequency spikes, similar to [Tutorial 1](https://github.com/sandialabs/WecOptTool/blob/main/examples/tutorial_1_WaveBot.ipynb).\n",
```

2024-10-29 16:18 UTC, dtgaebe commented on examples/tutorial_3_LUPA.ipynb
> +    "\n",
```suggestion
```

2024-10-29 19:46 UTC, merged